services:
  - type: web
    name: localai-fi-rc
    env: go
    # Force the build command to run where the actual main.go is
    buildCommand: "cd $BUILD_DIR && go build -o app main.go"
    # Start the compiled binary
    startCommand: "./app"
    envVars:
      - key: GO111MODULE
        value: "on"
      - key: GOPATH
        value: "/opt/render/project/go"

